spring:
  datasource:
    url: jdbc:mysql://db-j6ulg.pub-cdb.ntruss.com:3306/mirthon?serverTimezone=UTC&characterEncoding=UTF-8
    username: minjae
    password: minjae1234@
    driver-class-name: com.mysql.cj.jdbc.Driver
    read-only: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: bd9c7a5b1824856cb653477b896c35cc
            client-secret: WmGu0virUUzgbJUsZvQfTyJj7tlbjur3
            redirect-uri: http://localhost:5173/auth/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
    form-login:
      enabled=false:


  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
#  org.hibernate.type: trace


